### ISSUE TITLE
Cannot build/install project

### ISSUE THREAD

**Issue by cboecking** [fonoster/nodejs-voiceapp#2]
Hi Team,

I am having trouble installing this example per the directions. Here is what I did:

- Created a new ubuntu 22.04 container (via lxc) with ubuntu user having sudo capabilities
- sudo apt update
- sudo apt install git
- sudo apt install curl
- git clone https://github.com/fonoster/nodejs-voiceapp.git
- cd nodejs-voiceapp/
- cd
- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
- nvm install v18.15.0
- node -v
- npm -v
- cd nodejs-voiceapp/
- npm install ## this failed
- npm install -g node-gyp
- python3 -V
- sudo apt install make
- sudo apt install gcc
- npm install ## this failed

Will you kindly advise what else is needed to prepare my environment to successfully build this example?
Thanks, Chuck

**Comment by cboecking** [comment]
Here is the error message:
ubuntu@fonoster-03:~/nodejs-voiceapp$ npm install
npm WARN deprecated @opentelemetry/api-metrics@0.27.0: Please use @opentelemetry/api >= 1.3.0
npm WARN deprecated @opentelemetry/sdk-metrics-base@0.27.0: Please use @opentelemetry/sdk-metrics
npm ERR! code 127
npm ERR! path /home/ubuntu/nodejs-voiceapp/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c node build.js || nodejs build.js
npm ERR! make: Entering directory '/home/ubuntu/nodejs-voiceapp/node_modules/fibers/build'
npm ERR!   CXX(target) Release/obj.target/fibers/src/fibers.o
npm ERR! make: Leaving directory '/home/ubuntu/nodejs-voiceapp/node_modules/fibers/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.15.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/ubuntu/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/nodejs-voiceapp/node_modules/fibers/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/.cache/node-gyp/18.15.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/18.15.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/ubuntu/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/18.15.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/nodejs-voiceapp/node_modules/fibers',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: g++: No such file or directory
npm ERR! make: *** [fibers.target.mk:125: Release/obj.target/fibers/src/fibers.o] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.19.0-76051900-generic
npm ERR! gyp ERR! command "/home/ubuntu/.nvm/versions/node/v18.15.0/bin/node" "/home/ubuntu/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /home/ubuntu/nodejs-voiceapp/node_modules/fibers
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! sh: 1: nodejs: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2023-03-31T16_48_45_452Z-debug-0.log

**Comment by cboecking** [comment]
Created binding.gyp:
{
  "targets": [
    {
      "target_name": "binding",
      "sources": [ "src/binding.cc" ]
    }
  ]
}

This succeeds:
ubuntu@fonoster-03:~/nodejs-voiceapp$ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.15.0 | linux | x64
gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/ubuntu/.nvm/versions/node/v18.15.0/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/nodejs-voiceapp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.nvm/versions/node/v18.15.0/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.cache/node-gyp/18.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.cache/node-gyp/18.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/ubuntu/.nvm/versions/node/v18.15.0/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.cache/node-gyp/18.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/nodejs-voiceapp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok


This fails:
ubuntu@fonoster-03:~/nodejs-voiceapp$ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.15.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ubuntu/nodejs-voiceapp/build'
make: *** No rule to make target 'Release/obj.target/binding/src/binding.o', needed by 'Release/obj.target/binding.node'.  Stop.
make: Leaving directory '/home/ubuntu/nodejs-voiceapp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v18.15.0/lib/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.19.0-76051900-generic
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v18.15.0/bin/node" "/home/ubuntu/.nvm/versions/node/v18.15.0/bin/node-gyp" "build"
gyp ERR! cwd /home/ubuntu/nodejs-voiceapp
gyp ERR! node -v v18.15.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok

**Comment by psanders** [comment]
@YuriCodes @efraa 

This seems to be happening on a clean server.

Can we retrace the steps provided above?

We we also need to update the docs with troubleshooting steps.

@cboecking

While we triage this issue I created a [one-click](https://github.com/fonoster/nodejs-voiceapp#deploying-in-development-mode-with-gitpod) deployment using GitPod.

![gidpod](https://user-images.githubusercontent.com/539774/229375636-7d738df8-e555-488c-8e3b-95f55492be94.png)

This will launch the repo with GitPod and provide you with an URL for your voice application.

![ports](https://user-images.githubusercontent.com/539774/229375754-f08db949-8343-4fda-b2b3-ae28361bf59f.png)

Please, let me know if that helps unblock you.

**Comment by soulofmischief** [comment]
This doesn't seem to build on Node v20 on Apple Silicon either, having issues installing the `fibers` dependency. 

Glancing at the fiber repository, it seems it doesn't support Node.js 16 and above. Unfortunately, using `nvm` to run node < 16 didn't unblock me.

**Comment by psanders** [comment]
This comes up from time to time. I can see the error on my M1 with Node 20. However, it works fine with Node v16.17.0.

**Comment by psanders** [comment]
Closing as this was fix by [v0.3.29](https://github.com/fonoster/fonoster/commit/4661627569ffd8ca60b659ab2a1c1d5cdde5066e)
